import os
from dotenv import load_dotenv

load_dotenv()

COINCAP_API_KEY = os.getenv("COINCAP_API_KEY")
COINCAP_API_URL = os.getenv("COINCAP_API_URL")

GCP_PROJECT_ID = os.getenv("GCP_PROJECT_ID")
GCP_REGION = os.getenv("GCP_REGION")
GCP_INSTANCE_NAME = os.getenv("GCP_INSTANCE_NAME")
GCP_DB_NAME = os.getenv("GCP_DB_NAME")
GCP_DB_USER = os.getenv("GCP_DB_USER")
GCP_DB_PASSWORD = os.getenv("GCP_DB_PASSWORD")

DB_CONFIG = {
    "INSTANCE_CONNECTION_NAME": f"{GCP_PROJECT_ID}:{GCP_REGION}:{GCP_INSTANCE_NAME}",
    "DB_USER": GCP_DB_USER,
    "DB_PASSWORD": GCP_DB_PASSWORD,
    "DB_NAME": GCP_DB_NAME
}   